version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: 'nest-react-login-mongo-1'
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - nest-react-login
#    network_mode: "host"


  server:
    container_name: 'nest-react-login-server'
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: ./server/.env
    ports:
      - "3000:3000"
    volumes:
      - ./server/.env:/app/.env
    depends_on:
      - mongo
    networks:
      - nest-react-login

#  client:
#    container_name: 'nest-react-login-client'
#    build:
#      context: ./client
#      dockerfile: Dockerfile
#    ports:
#      - "3001:3001"
#    depends_on:
#      - server
#    networks:
#      - nest-react-login
#    network_mode: "host"

networks:
  nest-react-login:
    driver: bridge

volumes:
  mongo-data:
